-- ASKORAA V1 schema
-- Run this entire file in Supabase SQL Editor before using the app.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'ASKORAA User',
  bio text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.fields (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.user_fields (
  user_id uuid not null references public.profiles(id) on delete cascade,
  field_id bigint not null references public.fields(id) on delete cascade,
  field_name text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, field_id)
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check (kind in ('ASK','HELP')),
  title text not null check (char_length(title) between 3 and 140),
  body text not null check (char_length(body) between 3 and 5000),
  category text not null,
  status text not null default 'OPEN' check (status in ('OPEN','IN_PROGRESS','SOLVED','UNRESOLVED','CLOSED')),
  created_at timestamptz not null default now()
);

create table if not exists public.post_applications (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  applicant_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(post_id, applicant_id)
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  problem_owner_id uuid not null references public.profiles(id) on delete cascade,
  solver_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  category text not null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','SOLVED','UNRESOLVED','CLOSED')),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create unique index if not exists one_active_room_per_post
on public.rooms(post_id) where status = 'ACTIVE';

create table if not exists public.room_members (
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('OWNER','SOLVER')),
  joined_at timestamptz not null default now(),
  primary key(room_id,user_id),
  unique(room_id,role)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index if not exists messages_room_created_idx
on public.messages(room_id,created_at);

create table if not exists public.problem_outcomes (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null unique references public.rooms(id) on delete cascade,
  decided_by uuid not null references public.profiles(id) on delete cascade,
  outcome text not null check (outcome in ('YES','NO')),
  created_at timestamptz not null default now()
);

create table if not exists public.ratings (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  rater_id uuid not null references public.profiles(id) on delete cascade,
  rated_id uuid not null references public.profiles(id) on delete cascade,
  field text not null,
  rating integer not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  unique(room_id,rater_id)
);

insert into public.fields(name) values
('Business'),('Technology'),('Education'),('Career'),('Marketing'),('Design'),('Gaming'),('Electronics'),('Other')
on conflict(name) do nothing;

-- New-user profile creation.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id,display_name)
  values(new.id,coalesce(new.raw_user_meta_data->>'display_name','ASKORAA User'))
  on conflict(id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.fields enable row level security;
alter table public.user_fields enable row level security;
alter table public.posts enable row level security;
alter table public.post_applications enable row level security;
alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.messages enable row level security;
alter table public.problem_outcomes enable row level security;
alter table public.ratings enable row level security;

-- Profiles: public read, owner update.
create policy "profiles_select_public" on public.profiles
for select using (true);
create policy "profiles_update_self" on public.profiles
for update using (auth.uid()=id) with check (auth.uid()=id);

-- Fields public read.
create policy "fields_select_public" on public.fields
for select using (true);

-- User fields: owner manage, public read.
create policy "user_fields_select_public" on public.user_fields
for select using (true);
create policy "user_fields_insert_self" on public.user_fields
for insert with check (auth.uid()=user_id);
create policy "user_fields_delete_self" on public.user_fields
for delete using (auth.uid()=user_id);

-- Posts: public read, authenticated insert, owner update/delete.
create policy "posts_select_public" on public.posts
for select using (true);
create policy "posts_insert_auth" on public.posts
for insert with check (auth.uid()=author_id);
create policy "posts_update_owner" on public.posts
for update using (auth.uid()=author_id) with check (auth.uid()=author_id);
create policy "posts_delete_owner" on public.posts
for delete using (auth.uid()=author_id);

-- Applications: applicant can create/read own; post owner can read.
create policy "applications_insert_self" on public.post_applications
for insert with check (auth.uid()=applicant_id);
create policy "applications_select_participants" on public.post_applications
for select using (
  auth.uid()=applicant_id or
  exists(select 1 from public.posts p where p.id=post_id and p.author_id=auth.uid())
);

-- Rooms: only members can read; owner can create; members can update their room state only via client.
create policy "rooms_select_members" on public.rooms
for select using (
  auth.uid()=problem_owner_id or auth.uid()=solver_id
);
create policy "rooms_insert_owner" on public.rooms
for insert with check (auth.uid()=problem_owner_id);
create policy "rooms_update_owner" on public.rooms
for update using (auth.uid()=problem_owner_id) with check (auth.uid()=problem_owner_id);

-- Room membership: member can see own room membership; owner can insert members.
create policy "room_members_select_self" on public.room_members
for select using (auth.uid()=user_id);
create policy "room_members_select_owner" on public.room_members
for select using (exists(select 1 from public.rooms r where r.id=room_id and r.problem_owner_id=auth.uid()));
create policy "room_members_insert_owner" on public.room_members
for insert with check (exists(select 1 from public.rooms r where r.id=room_id and r.problem_owner_id=auth.uid()));

-- Messages: only room members can read/insert.
create policy "messages_select_member" on public.messages
for select using (exists(select 1 from public.room_members rm where rm.room_id=room_id and rm.user_id=auth.uid()));
create policy "messages_insert_member" on public.messages
for insert with check (
  auth.uid()=sender_id and
  exists(select 1 from public.room_members rm where rm.room_id=room_id and rm.user_id=auth.uid())
);

-- Outcomes: only room owner can insert/read; members can read.
create policy "outcomes_select_member" on public.problem_outcomes
for select using (
  exists(select 1 from public.room_members rm where rm.room_id=room_id and rm.user_id=auth.uid())
);
create policy "outcomes_insert_owner" on public.problem_outcomes
for insert with check (
  auth.uid()=decided_by and
  exists(select 1 from public.rooms r where r.id=room_id and r.problem_owner_id=auth.uid())
);

-- Ratings: participants can read; owner can rate solver.
create policy "ratings_select_participant" on public.ratings
for select using (
  exists(select 1 from public.room_members rm where rm.room_id=room_id and rm.user_id=auth.uid())
);
create policy "ratings_insert_owner" on public.ratings
for insert with check (
  auth.uid()=rater_id and
  exists(select 1 from public.rooms r where r.id=room_id and r.problem_owner_id=auth.uid() and r.solver_id=rated_id)
);

-- Realtime publication for chat.
do $$
begin
  begin
    alter publication supabase_realtime add table public.messages;
  exception when duplicate_object then
    null;
  end;
end $$;
