"use client";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import { useRouter } from "next/navigation";
const fields=["Business","Technology","Education","Career","Marketing","Design","Gaming","Electronics","Other"];
export default function Create(){
 const router=useRouter(); const [title,setTitle]=useState("");const [body,setBody]=useState("");const [category,setCategory]=useState(fields[0]);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(!data.user)router.push("/login?next=/create")})},[router]);
 async function submit(e:FormEvent){e.preventDefault();const t=title.trim(),b=body.trim();if(t.length<3||b.length<3){setMsg("Please explain the problem clearly.");return;}setBusy(true);setMsg("");const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login?next=/create");return;}const {error}=await supabase.from("posts").insert({author_id:user.id,title:t,body:b,kind:"ASK",category,status:"OPEN"});if(error){setMsg(error.message);setBusy(false);return;}router.push("/home");}
 return <main className="container narrow-page"><div className="form card create-modern"><span className="eyebrow">POST YOUR PROBLEM</span><h1>My problem is…</h1><p className="lead">Give another person enough context to understand what you need. If someone can genuinely help, you&apos;ll get a connection request.</p>{msg&&<div className="alert">{msg}</div>}<form onSubmit={submit}><label>What are you trying to solve?</label><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={140} placeholder="Example: How can I improve my shop sales?" required/><label>Tell us what&apos;s happening</label><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={5000} placeholder="What have you tried? What result do you want? Add useful context…" required/><label>Category</label><select value={category} onChange={e=>setCategory(e.target.value)}>{fields.map(f=><option key={f}>{f}</option>)}</select><div className="safety-inline"><b>Before you post</b><span>Keep passwords, OTPs, PINs, private documents and financial credentials out of the discussion.</span></div><button className="btn btn-large full" disabled={busy}>{busy?"Publishing…":"Publish My Problem"}</button></form></div></main>;
}
