"use client";
import { useEffect,useState } from "react";import Link from "next/link";import { supabase } from "../../lib/supabase";
export default function Profile(){const [user,setUser]=useState<any>(null);const [p,setP]=useState<any>(null);const [ratings,setRatings]=useState<any[]>([]);const [msg,setMsg]=useState("");
 const [avatarBusy,setAvatarBusy]=useState(false);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login?next=/profile";return;}setUser(user);const {data:profile,error}=await supabase.from("profiles").select("*").eq("id",user.id).single();if(error){setMsg(error.message);return;}setP(profile);const {data:r}=await supabase.from("ratings").select("id,rating,field,created_at,rater_id,profiles:rater_id(display_name)").eq("rated_id",user.id).order("created_at",{ascending:false});setRatings((r||[]) as unknown as any[])})()},[]);
 async function save(){if(!p)return;const {error}=await supabase.from("profiles").update({display_name:p.display_name,bio:p.bio}).eq("id",p.id);setMsg(error?error.message:"Profile saved successfully.")}
 async function changeAvatar(file:File){if(!p)return; if(!file.type.startsWith("image/")){setMsg("Please choose an image file.");return;} if(file.size>3*1024*1024){setMsg("Please choose an image smaller than 3 MB.");return;} setAvatarBusy(true);setMsg(""); try{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("Could not read image."));reader.readAsDataURL(file)}); const img=new Image(); img.onload=async()=>{const size=320;const canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Image processing is unavailable."); const scale=Math.max(size/img.width,size/img.height);const w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);const compressed=canvas.toDataURL("image/jpeg",0.82); if(compressed.length>900000)throw new Error("Please choose a simpler or smaller image."); const {error}=await supabase.from("profiles").update({avatar_url:compressed}).eq("id",p.id); if(error)throw new Error(error.message);setP({...p,avatar_url:compressed});setMsg("Profile picture updated.");setAvatarBusy(false)}; img.onerror=()=>{setMsg("Could not process that image.");setAvatarBusy(false)}; img.src=dataUrl;}catch(e:any){setMsg(e?.message||"Could not update profile picture.");setAvatarBusy(false)}}
 async function logout(){await supabase.auth.signOut();location.href="/home"}
 if(!p)return <main className="container"><div className="card loading-card">{msg||"Loading profile…"}</div></main>;
 const avg=ratings.length?ratings.reduce((s,r)=>s+r.rating,0)/ratings.length:0;
 return <main className="container profile-page"><section className="profile-hero card"><div className="profile-avatar-wrap"><div className="profile-avatar hex-avatar">{p.avatar_url?<img src={p.avatar_url} alt="Profile"/>:(p.display_name||"A").charAt(0).toUpperCase()}</div><label className="avatar-upload"><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)changeAvatar(f)}} disabled={avatarBusy}/>{avatarBusy?"Updating…":"Change photo"}</label></div><div><span className="eyebrow">MY PROFILE</span><h1>{p.display_name}</h1><p>{p.bio||"No bio yet. Tell people what you know and what you like helping with."}</p></div><button className="btn secondary" onClick={logout}>Logout</button></section><div className="grid2"><section className="card panel-card"><span className="eyebrow">EDIT</span><h2>Your public profile</h2>{msg&&<div className="success">{msg}</div>}<label>Name</label><input value={p.display_name||""} onChange={e=>setP({...p,display_name:e.target.value})}/><label>Bio</label><textarea value={p.bio||""} onChange={e=>setP({...p,bio:e.target.value})}/><button className="btn" onClick={save}>Save Profile</button></section><section className="card panel-card"><span className="eyebrow">TRUST</span><h2>Ratings received</h2><div className="rating-big"><b>{avg?avg.toFixed(1):"—"}</b><span>average from {ratings.length} rating{ratings.length===1?"":"s"}</span></div>{ratings.length===0?<div className="empty-inline">No ratings yet. Complete a Solve Room and useful contribution will appear here.</div>:ratings.map(r=><div className="rating-row" key={r.id}><div><strong>{r.profiles?.[0]?.display_name||"ASKORAA User"}</strong><span>{r.field} • {new Date(r.created_at).toLocaleDateString()}</span></div><b>{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</b></div>)}</section></div><section className="safety-card"><div><span className="eyebrow">YOUR PRIVACY</span><h2>Only share what you&apos;re comfortable making public.</h2><p>ASKORAA profiles are designed for useful contribution, not exposing private account information.</p></div><Link href="/settings" className="btn secondary">Settings</Link></section></main>;
}
