"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";

type Post={id:string;title:string;body:string;category:string;created_at:string;author_id:string;profiles?:{display_name:string|null;avatar_url?:string|null}[]|null};
export default function Solve(){const [posts,setPosts]=useState<Post[]>([]);const [user,setUser]=useState<any>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [msg,setMsg]=useState("");
 async function load(){setLoading(true);const {data:{user:u}}=await supabase.auth.getUser();setUser(u);const {data,error}=await supabase.from("posts").select("id,title,body,category,created_at,author_id,profiles:author_id(display_name,avatar_url)").eq("status","OPEN").eq("kind","ASK").order("created_at",{ascending:false}).limit(100);if(error)setMsg(error.message);else setPosts((data||[]) as unknown as Post[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function help(post:Post){if(!user){window.location.href="/login?next=/solve";return}if(user.id===post.author_id)return;setBusy(post.id);const {error}=await supabase.from("post_applications").insert({post_id:post.id,applicant_id:user.id});if(error)setMsg(error.code==="23505"?"You already offered help on this problem.":error.message);else setMsg("I CAN HELP sent. The owner has been notified.");setBusy(null)}
 const others=posts.filter(p=>p.author_id!==user?.id);return <main className="container"><section className="page-heading"><span className="eyebrow">SOLVE SOMEONE'S PROBLEM</span><h1>Use what you know.</h1><p>These are open problems from other ASKORAA users. Your own problems are never offered here as something you can solve yourself.</p></section>{msg&&<div className="toast-note">{msg}</div>}{loading?<div className="card loading-card">Finding problems you can help with…</div>:others.length===0?<div className="empty-large card"><div className="empty-icon">🤝</div><h3>No matching problems right now</h3><p>Check back later or explore the public archive.</p><Link href="/archive" className="btn secondary">Open Archive</Link></div>:<div className="problem-list">{others.map(p=><article className="problem-card" key={p.id}><div className="problem-top"><span className="category-chip">{p.category}</span><span className="status-dot"><i/> OPEN</span></div><Link href={`/post/${p.id}`} className="problem-title">{p.title}</Link><p>{p.body.length>300?p.body.slice(0,300)+"…":p.body}</p><div className="problem-bottom"><span className="author-line"><span className="mini-avatar hex-avatar">{p.profiles?.[0]?.avatar_url?<img src={p.profiles[0].avatar_url} alt=""/>:(p.profiles?.[0]?.display_name||"A").charAt(0).toUpperCase()}</span>{p.profiles?.[0]?.display_name||"ASKORAA User"} <span>•</span>{new Date(p.created_at).toLocaleDateString()}</span><button className="btn btn-sm" disabled={busy===p.id} onClick={()=>help(p)}>{busy===p.id?"Sending…":"I CAN HELP"}</button></div></article>)}</div>}</main>}
